### ISSUE TITLE
Travis job is not running when ".travis.yml" file is changed

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/codechain#1709] opened 2019-07-22 05:09 UTC
https://travis-ci.org/CodeChain-io/codechain/jobs/560424198

```
TRAVIS_EVENT_TYPE=pull_request
TRAVIS_BRANCH=dynamic-test
TRAVIS_COMMIT=6ce23a3df2a661051d7ce270abea4a09c10f984e
TRAVIS_COMMIT_RANGE=e2b76bc70c0bd517fba7ff406c94128fd11e08b5...b17e3e9c23446830cfb35c64e80a32bb61a7ceb9
+case ${TRAVIS_EVENT_TYPE} in
+echo 'Pull request'
Pull request
+COMMIT_RANGE=e2b76bc70c0bd517fba7ff406c94128fd11e08b5...b17e3e9c23446830cfb35c64e80a32bb61a7ceb9
+git log --oneline --decorate --all --graph
+head -n 10
*   5c3662d (HEAD) Merge b17e3e9c23446830cfb35c64e80a32bb61a7ceb9 into 38eefa35f6d088223c828b2fda9403fe1a9db002
|\  
| * b17e3e9 Run dynamic test in Travis
* |   38eefa3 Merge branch 'master' into dynamic-test
|\ \  
| |/  
|/|   
| * 5936aac (origin/master, origin/HEAD, master) Don't panic if the max_num is equal to the min_num for validators
| * 4e02386 Update Dynamic-Validator.md
| * ae49c41 Add detail for dynamic validator election algorithm document
+echo 'Check changes for: e2b76bc70c0bd517fba7ff406c94128fd11e08b5...b17e3e9c23446830cfb35c64e80a32bb61a7ceb9'
Check changes for: e2b76bc70c0bd517fba7ff406c94128fd11e08b5...b17e3e9c23446830cfb35c64e80a32bb61a7ceb9
+set +e
+git diff --name-only e2b76bc70c0bd517fba7ff406c94128fd11e08b5...b17e3e9c23446830cfb35c64e80a32bb61a7ceb9
+grep -qvE '^spec/|\.md$'
fatal: Invalid symmetric difference expression e2b76bc70c0bd517fba7ff406c94128fd11e08b5...b17e3e9c23446830cfb35c64e80a32bb61a7ceb9
+case $? in
+echo 'Only '\''^spec/|\.md$'\'' were updated, or there'\''s no change, not running the CI.'
Only '^spec/|\.md$' were updated, or there's no change, not running the CI.
+skip_travis
+return_to_travis skip
+STRATEGY=skip
+echo skip
+exit 0
```

**Comment by foriequal0** [comment] 2019-07-24 05:30
"fatal: Invalid symmetric difference expression" error is only thrown when the object does not exist (see below)
https://github.com/git/git/blob/9c9b961d7eb15fb583a2a812088713a68a85f1c0/revision.c#L1779
https://stackoverflow.com/questions/52671673/git-error-trying-to-retrieve-log-messages
The error is caused by the command `git diff --name-only e2b76bc70c0bd517fba7ff406c94128fd11e08b5...b17e3e9c23446830cfb35c64e80a32bb61a7ceb9` and e2b76bc70c0bd517fba7ff406c94128fd11e08b5 is not in the history.

Fortunately, the object(e2b76bc70c0bd517fba7ff406c94128fd11e08b5) haven't GC'd on my local and Github temporaily.
```
commit e2b76bc70c0bd517fba7ff406c94128fd11e08b5
Merge: f453025f 4e023868
Author: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
Date:   Thu Jul 18 10:54:04 2019 +0000

    Merge branch 'master' into dynamic-test
```

This commit is made by mergify[bot], and it is related to [this PR](https://github.com/CodeChain-io/codechain/pull/1699). I've force-pushed and made new merge commit to remove `mergify[bot]`'s commit that made CLAHub fail. (You can glimpse the history)
```
commit 38eefa35f6d088223c828b2fda9403fe1a9db002
Merge: f453025f 5936aacf
Author: foriequal0 <sclee@codechain.io>
Date:   Fri Jul 19 11:15:43 2019 +0900

    Merge branch 'master' into dynamic-test
```

The job might be triggered right after Mergify made a merge commit. But I've deleted the commit before the job actually started. Then the error can be occured.

**Comment by foriequal0** [comment] 2019-07-24 06:19
I've made a PR. It'll prevent a Travis CI job from being marked as success when an error occurs

**Closed** 2019-07-25 03:03 UTC
Labels: test
