### ISSUE TITLE
Add linux build to Travis

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain#211] opened 2018-06-18 07:13 UTC
Currently, Travis only builds Mac OS X binary. Add Linux build.

**Comment by sgkim126** [comment] 2018-06-18 07:19
FYI, the linux build was removed because of the test failed that is not reproduced in the local environment.

**Comment by joojis** [comment] 2018-06-19 12:03
It seems no problem for now. https://travis-ci.org/joojis/codechain/jobs/394063675

I'm going to make a PR for it. Any comment? @kseo @sgkim126

**Comment by kseo** [comment] 2018-06-20 00:41
@joojis Let's do it.

**Comment by joojis** [comment] 2018-06-20 01:55
Merged. https://github.com/CodeChain-io/codechain/pull/216

**Closed by joojis** 2018-06-20 01:55 UTC
